In [28]:
import numpy as np

In [29]:
def angle(a,b,c):
    BA = a - b
    BC = c - b
    
    
    dot_product = np.dot(BA, BC)
    
    
    x=np.linalg.norm(BA)
    y=np.linalg.norm(BC)
    
    
    cos_angle=dot_product/(x*y)
    
    angle_in_degrees=np.degrees(np.arccos(cos_angle))
    
    return angle_in_degrees

In [31]:
N = []
c=0
with open('C:/Users/meenu.DESKTOP-FACTER5/Desktop/193l.pdb') as infile:
    for line in infile:
        if line[17:21]=="GLY " and line[:4] == 'ATOM' and (line[77:79]=='N ' or line[77:79]=='CA' or line[77:79]=='C ' or line[77:79]=='O '):
            try:
                pl=[float(line[31:39]), float(line[39:47]), float(line[47:55])]
                                        
                N.append(pl)
            except NameError:
                print("Error")
                
cd=np.array(N)
        

for i in range(1,len(cd),4):
    print('N-CA-C <',cd[i-1],'\n\t',cd[i],'\n\t',cd[i+1],'\n')
    x=angle(cd[i-1],cd[i],cd[i+1])
    print('Angle N-CA-C = ',x,'\n')
    
    for j in range(i+1,i+2):        
        print('CA-C-O <',cd[j-1],'\n\t',cd[j],'\n\t',cd[j+1],'\n\n')
        y=angle(cd[j-1],cd[j],cd[j+1])
        print('Angle CA-C-O = ',y,'\n')
        
        

N-CA-C < [-2.38  15.983  5.406] 
	 [-2.709 17.044  4.471] 
	 [-3.444 18.088  5.267] 

Angle N-CA-C =  106.0841178137324 

CA-C-O < [-2.709 17.044  4.471] 
	 [-3.444 18.088  5.267] 
	 [-3.975 17.771  6.343] 


Angle CA-C-O =  119.37109137024328 

N-CA-C < [-13.105  16.769  18.317] 
	 [-13.657  17.828  19.153] 
	 [-12.859  19.091  19.409] 

Angle N-CA-C =  120.18671684971096 

CA-C-O < [-13.657  17.828  19.153] 
	 [-12.859  19.091  19.409] 
	 [-13.129  19.814  20.377] 


Angle CA-C-O =  120.25568600186321 

N-CA-C < [-12.985  27.829  23.02 ] 
	 [-13.144  29.015  22.199] 
	 [-12.18   29.174  21.028] 

Angle N-CA-C =  116.76620210007883 

CA-C-O < [-13.144  29.015  22.199] 
	 [-12.18   29.174  21.028] 
	 [-12.187  30.215  20.357] 


Angle CA-C-O =  120.00312596853384 

N-CA-C < [-9.326 26.615 12.686] 
	 [-8.193 27.206 11.989] 
	 [-6.996 27.455 12.893] 

Angle N-CA-C =  113.238381911919 

CA-C-O < [-8.193 27.206 11.989] 
	 [-6.996 27.455 12.893] 
	 [-5.858 27.373 12.456] 


Angle CA-C-O =  

In [26]:
#type(cd)

numpy.ndarray

In [15]:
#len(cd)

48